name: Building and pushing Auth service image to Docker Hub

on:
  workflow_dispatch:
  pull_request: 
    types: [closed]
    branches:
      - main
    paths:
      - 'auth-service/**'
  push:
    branches:
      - main
    paths:
      - 'auth-service/**'

jobs:
  building:
    name: Building Auth service image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Build Auth service image
        run: docker build -t perazzojoao/auth_app-auth-service:latest -f auth-service/auth-service.Dockerfile auth-service

      - name: Push Auth service image to Docker Hub
        run: |
          docker login -u perazzojoao -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push perazzojoao/auth_app-auth-service:latest