name: Building and pushing Mail service image to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'mail-service/**'

jobs:
  building:
    name: Building Mail service image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Build Mail service image
        run: docker build -t perazzojoao/auth_app-mail-service:latest -f mail-service/mail-service.Dockerfile mail-service

      - name: Push Mail service image to Docker Hub
        run: |
          docker login -u perazzojoao -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push perazzojoao/auth_app-mail-service:latest