name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses:  docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Set up Golang v1.22
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Run tests
        run: go test -timeout 30s -run ^TestAuthService$ authApp/cmd/user -v
